import 'styles/globals.scss';
import 'styles/App.scss';

export const metadata = {
  title: 'Main',
  description: 'Generated by create next app',
};

type LayoutProps = {
  children?: React.ReactNode;
};

let Layout = (props: LayoutProps) => {
  let { children } = props;

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, width=device-width" />
        <meta name="theme-color" content="#0b0b16" />
      </head>
      <body>
        <div id="__next">{children}</div>
      </body>
    </html>
  );
};

export default Layout;
